/**
 * Devnet configuration — generated by scripts/bootstrap-pool.ts
 *
 * All values are public addresses (no secrets).
 * Import this instead of hardcoding addresses in components.
 *
 * Re-generate after bootstrap: cd scripts && npm run bootstrap
 */

import config from "./devnet-config.json";

export const PROGRAM_ID: string = config.programId;
export const POOL_PDA: string = config.pool;
export const POLICY_PDA: string = config.policy;
export const ALLOWLIST_PDA: string = config.allowlist;

export const MINTS: Record<string, string> = Object.freeze(config.mints);
export const VAULTS: Record<string, string> = Object.freeze(config.vaults);

/** Tick account addresses — required as remaining_accounts for swaps */
export const TICK_ADDRESSES: string[] = (config.ticks ?? []).map(
  (t: { address: string }) => t.address,
);

export const DEVNET_CONFIG = Object.freeze(config);
